### ISSUE TITLE
permissions doesn't work

### ISSUE THREAD

**Issue by ABotDev** [moonstar-x/discord-downtime-notifier#11]

**Comment by moonstar-x** [comment]
Hey there, can you be a bit more descriptive? What do you mean that permissions don't work?

**Comment by ABotDev** [comment]
so i changed the permissions to manage_messages but people without the permission can use it 2

**Comment by moonstar-x** [comment]
When you say that you changed the permissions, you mean that you changed the code to check for MANAGE_MESSAGES instead of ADMINISTRATOR?

**Comment by ABotDev** [comment]
i changed the code so you don't need admin but manage_messages but then everyone can use the command.

**Comment by moonstar-x** [comment]
Are you doing this:

```js
module.exports = {
  name: 'add',
  description: 'Add a new bot to the downtime check list.',
  emoji: ':heavy_plus_sign: ',
  requiredPermissions: PERMISSIONS.manageMessages,
  execute(message, options) {
```

or:

```js
module.exports = {
  name: 'add',
  description: 'Add a new bot to the downtime check list.',
  emoji: ':heavy_plus_sign: ',
  requiredPermissions: "manage_messages",
  execute(message, options) {
```

?

**Comment by ABotDev** [comment]
i will

**Comment by moonstar-x** [comment]
> i will

My question was: which one of the two were you using?

**Comment by ABotDev** [comment]
non of them lmfao 
but thanks for the help the first one works
