### ISSUE TITLE
[BOT]  The bot is offline

### ISSUE THREAD

**Issue by Romvnly-Gaming** [moonstar-x/discord-downtime-notifier#16]
AY FAM, THE BOT THAT'S SUPPOSED TO BE MONITORING MY DOWNTIME IS DOWN 😭 

take your time getting it up, im chillin

if the bot couldn't be hosted anymore im sad

**Comment by moonstar-x** [comment]
Yeah sorry man, the thing is that Heroku discontinued the database addon I was using some time ago. I need to find a replacement first. Anyways sorry for taking too long. 😢

**Comment by Romvnly-Gaming** [comment]
RIP it's okay 😭

**Comment by moonstar-x** [comment]
Sorry for the tremendous wait. I've been hella busy with college.

In any case, I'm currently trying out MongoDB Atlas and it seems to be working wonders even on its free tier.

With that said, the bot is updated and back online! 😄
