### ISSUE TITLE
announcement channels doesnt count as text channels

### ISSUE THREAD

**Issue by 1Euro7Cent** [moonstar-x/discord-downtime-notifier#17]
![Bild_2021-03-06_182606](https://user-images.githubusercontent.com/67194495/110215320-6a203300-7ea9-11eb-9e5f-a64001b7a59a.png)

**Comment by moonstar-x** [comment]
You're right, I made the bot long before there were news channels. Gimme a sec.

**Comment by moonstar-x** [comment]
This should be fixed in #18, though I have no servers that have access to announcement channels. When you're available,

* Run `git pull origin master`
* Restart the bot

And check if it works. Thanks!

**Comment by 1Euro7Cent** [comment]
im using the public one

**Comment by 1Euro7Cent** [comment]
and it workes

**Comment by moonstar-x** [comment]
> im using the public one

Uhhh, the public one that I host is currently offline because I still gotta find a mongoDB service and migrate what I had. I do not host the instance that you showed me on the screenshot.

**Comment by 1Euro7Cent** [comment]
uhmmmm i got it from here https://top.gg/bot/805140305506074685

**Comment by moonstar-x** [comment]
Yeah I figured there are others hosting this since it's open source. In any case, I'm glad that the maintainer for that bot is listening for updates and reflecting them on their own instance.

Thanks anyways for the report and I'm glad it works now. Hope you have a great day!
