### ISSUE TITLE
Wont Post The downtime 

### ISSUE THREAD

**Issue by NOXITB** [moonstar-x/discord-downtime-notifier#23]
Hi the bot wont post when a bot goes offline can i get some help please

**Comment by AtomicGaming666** [comment]
do yours post when th bots come online or just dont it post at all

**Comment by moonstar-x** [comment]
I'm gonna close this as it seems to be a duplicate of #22. Please check the solution suggested in that issue.

If you feel like this issue is not a duplicate of the aforementioned one, feel free to re-open it.
